# Generated by Django 5.2.3 on 2025-08-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='cardholder_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cardholder Name'),
        ),
        migrations.AlterField(
            model_name='usercard',
            name='last_four_digits',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Last Four Digits'),
        ),
    ]
