# Generated by Django 5.2.3 on 2025-08-19 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_usercard_brand_alter_usercard_cardholder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.usercard', verbose_name='Card'),
        ),
    ]
